class Loan:
    def __init__(self):
        '''
        self.id
        self.member_id
        self.loan_amount
        self.funded_amount
        self.funded_amount_investors
        self.term
        self.interest_rate
        self.installment
        self.grade
        self.sub_grade
        self.employee_title
        self.employment_length
        self.home_ownership
        self.annual_income
        self.is_income_verified
        self.issue_date
        self.loan_status
        self.payment_plan
        self.url
        self.description
        self.purpose
        self.title
        self.zip_code
        self.address_state
        self.debt_to_income
        self.delinq_2yrs
        self.earliest_credit_line
        self.inq_last_6mths
        self.mths_since_last_delinq
        self.mth_since_last_record
        self.open_credit_lines
        self.public_records
        self.revolving_balance
        self.revolving_util
        self.total_accounts
        self.initial_list_status
        self.outstanding_principal
        self.outstanding_principal_investors
        self.total_payment
        self.total_payment_investors
        self.total_received_principal
        self.total_received_interest
        self.total_received_late_fees
        self.recoveries
        self.collection_recovery_fee
        self.last_payment_date
        self.last_payment_amount
        self.next_payment_date
        self.last_credit_pulled_date
        self.collections_12_mths
        self.mths_since_last_major_derog
        self.policy_code
        '''
        
