"""empty message

Revision ID: 130ac7a73b26
Revises: None
Create Date: 2015-02-12 20:52:08.033409

"""

# revision identifiers, used by Alembic.
revision = '130ac7a73b26'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('loan_amount', sa.Integer(), nullable=True),
    sa.Column('funded_amount', sa.Integer(), nullable=True),
    sa.Column('funded_amount_investors', sa.Float(), nullable=True),
    sa.Column('term', sa.Integer(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('installment', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(), nullable=True),
    sa.Column('sub_grade', sa.String(), nullable=True),
    sa.Column('employee_title', sa.String(), nullable=True),
    sa.Column('employment_length', sa.Integer(), nullable=True),
    sa.Column('home_ownership', sa.String(), nullable=True),
    sa.Column('annual_income', sa.Float(), nullable=True),
    sa.Column('is_income_verified', sa.Boolean(), nullable=True),
    sa.Column('issue_date', sa.DateTime(), nullable=True),
    sa.Column('loan_status', sa.String(), nullable=True),
    sa.Column('payment_plan', sa.Boolean(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('zip_code', sa.String(), nullable=True),
    sa.Column('address_state', sa.String(), nullable=True),
    sa.Column('debt_to_income', sa.Float(), nullable=True),
    sa.Column('delinq_2yrs', sa.Integer(), nullable=True),
    sa.Column('earliest_credit_line', sa.DateTime(), nullable=True),
    sa.Column('inq_last_6mths', sa.Integer(), nullable=True),
    sa.Column('mths_since_last_delinq', sa.Integer(), nullable=True),
    sa.Column('mth_since_last_record', sa.Integer(), nullable=True),
    sa.Column('open_credit_lines', sa.Integer(), nullable=True),
    sa.Column('public_records', sa.Integer(), nullable=True),
    sa.Column('revolving_balance', sa.Integer(), nullable=True),
    sa.Column('revolving_util', sa.Float(), nullable=True),
    sa.Column('total_accounts', sa.Integer(), nullable=True),
    sa.Column('initial_list_status', sa.String(), nullable=True),
    sa.Column('outstanding_principal', sa.Float(), nullable=True),
    sa.Column('outstanding_principal_investors', sa.Float(), nullable=True),
    sa.Column('total_payment', sa.Float(), nullable=True),
    sa.Column('total_payment_investors', sa.Float(), nullable=True),
    sa.Column('total_received_principal', sa.Float(), nullable=True),
    sa.Column('total_received_interest', sa.Float(), nullable=True),
    sa.Column('total_received_late_fees', sa.Float(), nullable=True),
    sa.Column('recoveries', sa.Float(), nullable=True),
    sa.Column('collection_recovery_fee', sa.Float(), nullable=True),
    sa.Column('last_payment_date', sa.DateTime(), nullable=True),
    sa.Column('last_payment_amount', sa.Float(), nullable=True),
    sa.Column('next_payment_date', sa.DateTime(), nullable=True),
    sa.Column('last_credit_pulled_date', sa.DateTime(), nullable=True),
    sa.Column('collections_12_mths', sa.Integer(), nullable=True),
    sa.Column('mths_since_last_major_derog', sa.Integer(), nullable=True),
    sa.Column('policy_code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    ### end Alembic commands ###
