"""empty message

Revision ID: 1b8be65eff29
Revises: None
Create Date: 2015-02-08 22:19:01.814366

"""

# revision identifiers, used by Alembic.
revision = '1b8be65eff29'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('loans')
    ### end Alembic commands ###
