"""empty message

Revision ID: 22bbd75e514b
Revises: 1e00f3edeb11
Create Date: 2015-02-14 16:58:52.557810

"""

# revision identifiers, used by Alembic.
revision = '22bbd75e514b'
down_revision = '1e00f3edeb11'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('mths_since_last_record', sa.Integer(), nullable=True))
    op.drop_column('loans', 'mth_since_last_record')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('mth_since_last_record', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('loans', 'mths_since_last_record')
    ### end Alembic commands ###
