"""empty message

Revision ID: 2d55be79f4bd
Revises: 1b8be65eff29
Create Date: 2015-02-11 14:08:59.997898

"""

# revision identifiers, used by Alembic.
revision = '2d55be79f4bd'
down_revision = '1b8be65eff29'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('member_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'member_id')
    ### end Alembic commands ###
