"""empty message

Revision ID: 48a87d823997
Revises: 54a2b7d15c25
Create Date: 2015-02-16 10:04:53.357778

"""

# revision identifiers, used by Alembic.
revision = '48a87d823997'
down_revision = '54a2b7d15c25'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rejected_loans', 'risk_score')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rejected_loans', sa.Column('risk_score', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
