"""empty message

Revision ID: 728d3e698cf
Revises: 2d55be79f4bd
Create Date: 2015-02-11 14:28:36.499826

"""

# revision identifiers, used by Alembic.
revision = '728d3e698cf'
down_revision = '2d55be79f4bd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loans', sa.Column('address_state', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('annual_income', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('collection_recovery_fee', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('collections_12_mths', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('debt_to_income', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('delinq_2yrs', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('description', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('earliest_credit_line', sa.DateTime(), nullable=True))
    op.add_column('loans', sa.Column('employee_title', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('employment_length', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('funded_amount', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('funded_amount_investors', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('grade', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('home_ownership', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('initial_list_status', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('inq_last_6mths', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('installment', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('interest_rate', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('is_income_verified', sa.Boolean(), nullable=True))
    op.add_column('loans', sa.Column('issue_date', sa.DateTime(), nullable=True))
    op.add_column('loans', sa.Column('last_credit_pulled_date', sa.DateTime(), nullable=True))
    op.add_column('loans', sa.Column('last_payment_amount', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('last_payment_date', sa.DateTime(), nullable=True))
    op.add_column('loans', sa.Column('loan_amount', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('loan_status', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('mth_since_last_record', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('mths_since_last_delinq', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('mths_since_last_major_derog', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('next_payment_date', sa.DateTime(), nullable=True))
    op.add_column('loans', sa.Column('open_credit_lines', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('outstanding_principal', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('outstanding_principal_investors', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('payment_plan', sa.Boolean(), nullable=True))
    op.add_column('loans', sa.Column('policy_code', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('public_records', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('purpose', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('recoveries', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('revolving_balance', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('revolving_util', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('sub_grade', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('term', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('title', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('total_accounts', sa.Integer(), nullable=True))
    op.add_column('loans', sa.Column('total_payment', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('total_payment_investors', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('total_received_interest', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('total_received_late_fees', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('total_received_principal', sa.Float(), nullable=True))
    op.add_column('loans', sa.Column('url', sa.String(), nullable=True))
    op.add_column('loans', sa.Column('zip_code', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loans', 'zip_code')
    op.drop_column('loans', 'url')
    op.drop_column('loans', 'total_received_principal')
    op.drop_column('loans', 'total_received_late_fees')
    op.drop_column('loans', 'total_received_interest')
    op.drop_column('loans', 'total_payment_investors')
    op.drop_column('loans', 'total_payment')
    op.drop_column('loans', 'total_accounts')
    op.drop_column('loans', 'title')
    op.drop_column('loans', 'term')
    op.drop_column('loans', 'sub_grade')
    op.drop_column('loans', 'revolving_util')
    op.drop_column('loans', 'revolving_balance')
    op.drop_column('loans', 'recoveries')
    op.drop_column('loans', 'purpose')
    op.drop_column('loans', 'public_records')
    op.drop_column('loans', 'policy_code')
    op.drop_column('loans', 'payment_plan')
    op.drop_column('loans', 'outstanding_principal_investors')
    op.drop_column('loans', 'outstanding_principal')
    op.drop_column('loans', 'open_credit_lines')
    op.drop_column('loans', 'next_payment_date')
    op.drop_column('loans', 'mths_since_last_major_derog')
    op.drop_column('loans', 'mths_since_last_delinq')
    op.drop_column('loans', 'mth_since_last_record')
    op.drop_column('loans', 'loan_status')
    op.drop_column('loans', 'loan_amount')
    op.drop_column('loans', 'last_payment_date')
    op.drop_column('loans', 'last_payment_amount')
    op.drop_column('loans', 'last_credit_pulled_date')
    op.drop_column('loans', 'issue_date')
    op.drop_column('loans', 'is_income_verified')
    op.drop_column('loans', 'interest_rate')
    op.drop_column('loans', 'installment')
    op.drop_column('loans', 'inq_last_6mths')
    op.drop_column('loans', 'initial_list_status')
    op.drop_column('loans', 'home_ownership')
    op.drop_column('loans', 'grade')
    op.drop_column('loans', 'funded_amount_investors')
    op.drop_column('loans', 'funded_amount')
    op.drop_column('loans', 'employment_length')
    op.drop_column('loans', 'employee_title')
    op.drop_column('loans', 'earliest_credit_line')
    op.drop_column('loans', 'description')
    op.drop_column('loans', 'delinq_2yrs')
    op.drop_column('loans', 'debt_to_income')
    op.drop_column('loans', 'collections_12_mths')
    op.drop_column('loans', 'collection_recovery_fee')
    op.drop_column('loans', 'annual_income')
    op.drop_column('loans', 'address_state')
    ### end Alembic commands ###
